# Generated by Django 3.2.7 on 2022-04-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('home_team_red_cards', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team_red_cards', models.CharField(blank=True, max_length=45, null=True)),
                ('goals_home', models.CharField(blank=True, max_length=45, null=True)),
                ('goals_away', models.CharField(blank=True, max_length=45, null=True)),
                ('season', models.CharField(blank=True, max_length=45, null=True)),
                ('match_date', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('home_team_possession', models.CharField(blank=True, max_length=45, null=True)),
                ('away_team_possession', models.CharField(blank=True, max_length=45, null=True)),
                ('home_team_shots', models.CharField(blank=True, max_length=45, null=True)),
                ('away_team_shots', models.CharField(blank=True, max_length=45, null=True)),
                ('home_team_yellow_cards', models.CharField(blank=True, max_length=45, null=True)),
                ('away_team_yellow_cards', models.CharField(blank=True, max_length=45, null=True)),
                ('home_team_fouls', models.CharField(blank=True, max_length=45, null=True)),
                ('away_team_fouls', models.CharField(blank=True, max_length=45, null=True)),
                ('home_team', models.CharField(max_length=45)),
                ('away_team', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'match_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=50, primary_key=True, serialize=False)),
                ('player_position', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=50, null=True)),
                ('height', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=50, null=True)),
                ('date_of_birth', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=50)),
                ('weight', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=20, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('record_league_attendance', models.CharField(blank=True, max_length=100, null=True)),
                ('building_date', models.CharField(blank=True, max_length=100, null=True)),
                ('pitch_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'stadium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerClubSeason',
            fields=[
                ('player_name', models.OneToOneField(db_column='player_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='premier_league.player')),
                ('season', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'player_club_season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('fan_username', models.OneToOneField(db_column='fan_username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='premier_league.fan')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.CharField(blank=True, max_length=255, null=True)),
                ('match_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
